# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  GLAD_config = debug
  ImGui_config = debug
  Engine_config = debug
  ExampleGame_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  GLAD_config = release
  ImGui_config = release
  Engine_config = release
  ExampleGame_config = release

else ifeq ($(config),distribution)
  GLFW_config = distribution
  GLAD_config = distribution
  ImGui_config = distribution
  Engine_config = distribution
  ExampleGame_config = distribution

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW GLAD ImGui Engine ExampleGame

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLAD GLFW ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/GLAD -f Makefile config=$(GLAD_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Engine/vendor/imgui -f Makefile config=$(ImGui_config)
endif

Engine: GLFW GLAD ImGui
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

ExampleGame: Engine GLFW GLAD ImGui
ifneq (,$(ExampleGame_config))
	@echo "==== Building ExampleGame ($(ExampleGame_config)) ===="
	@${MAKE} --no-print-directory -C ExampleGame -f Makefile config=$(ExampleGame_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/GLAD -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C ExampleGame -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  distribution"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo "   ImGui"
	@echo "   Engine"
	@echo "   ExampleGame"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"